baseURL = "https://karuppiah7890.github.io/blog"
languageCode = "en-us"
title = "Karuppiah's Blog"
theme = "ananke"
publishDir = "docs"
disqusShortname = "karuppiah-blog"
staticDir = ["static"]

[params]
  twitter = "https://twitter.com/karuppiah7890"
  github = "https://github.com/karuppiah7890"
  youtube = "https://www.youtube.com/channel/UC8RUp-TYJUhTzgAgPqDKRRg"
